In [1]:
from assignment_rise.models.roberta import ROBERTA
from assignment_rise.utils.labels import SYSTEM_A_LABELS_ID, SYSTEM_B_LABELS_ID

roberta_A = ROBERTA('../lora_system_A/', labels_id=SYSTEM_A_LABELS_ID)
roberta_B = ROBERTA('../lora_system_B/', labels_id=SYSTEM_B_LABELS_ID)

/archive/projects/a.ihsan/assignment-rise/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/archive/projects/a.ihsan/assignment-rise/.venv/lib/python3.10/site-packages/transformers/utils/hub.py:123: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [2]:
text = 'Ahmad Ihsan plays the Fender Stratocaster guitar.'
df_A = roberta_A.predict_tags(text)
df_A

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
tokens,<s>,ĠAhmad,ĠI,hs,an,Ġplays,Ġthe,ĠF,ender,ĠStrat,oc,aster,Ġguitar,.,</s>
tags,O,B-PER,I-PER,I-PER,I-PER,O,O,B-INST,I-INST,I-INST,I-INST,I-INST,O,O,O

In [3]:
text_list = ['Ahmad', 'Ihsan', 'works', 'at', 'FZ Jülich GmbH', '.']
df_B = roberta_B.predict_tags(text_list)
df_B

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
tokens,<s>,ĠAhmad,ĠI,hs,an,Ġworks,Ġat,ĠF,Z,ĠJ,Ã¼,lich,ĠG,mb,H,Ġ.,</s>
tags,O,B-PER,I-PER,I-PER,I-PER,O,O,B-ORG,I-ORG,I-ORG,I-ORG,I-ORG,I-ORG,I-ORG,I-ORG,O,O